### ISSUE TITLE
help how to fix ! Could not pass event BlockPlaceEvent to Cenix v1.0

### ISSUE THREAD

**Issue by meowss2** [MC-Jinky/Cenix#9]
[11:54:20] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to Cenix v1.0
java.util.NoSuchElementException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_212]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_212]
	at me.jinky.checks.blocks.PlaceCheck.performCheck(PlaceCheck.java:40) ~[?:?]
	at me.jinky.Cenix.onPlace(Cenix.java:209) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-134]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:324) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:231) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:502) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1398) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-134]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]

**Comment by MC-Jinky** [comment]
**Please provide the following so I can look into this:**
Server Version. (Exact output of /ver)
CraftBukkit, Spigot, or PaperSpigot
List of all plugins on the server

**Comment by MC-Jinky** [comment]
Fixed in newer versions of Cenix
